pipeline {
    agent any

    environment {
        APP_REPO = 'https://github.com/a1dellahi/covoiti-back.git'
        BRANCH = 'develop'
        GIT_CREDENTIALS = 'github-coivoiti-pat'
    }

    tools {
        maven 'maven-3.9.9' 
    }

    stages {
        stage('Checkout App Code') {
            steps {
                git credentialsId: "${GIT_CREDENTIALS}", url: "${APP_REPO}", branch: "${BRANCH}"
            }
        }

        stage('Build with Maven') {
            steps {
                sh 'mvn clean install -DskipTests=true'
            }
        }

        stage('Run Unit Tests') {
            steps {
                sh 'mvn test'
            }
        }

        stage('Package App') {
            steps {
                sh 'mvn package'
            }
        }

        stage('Build image') {
            steps {
                sh 'echo "Builduing image..."'
            }
        }

        stage('Deploy on K8s') {
            steps {
                sh 'echo "Deploying app..."'
            }
        }
    }

    post {
        success {
            echo 'Build and tests succeeded!'
        }
        failure {
            echo 'Build or tests failed.'
        }
    }
}
