pipeline {
    agent any
        

    stages {

    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Build or test failed.'
        }

    }
}
